### PR TITLE
Add export api, modified create&get package info

### PR DESCRIPTION
**Pull request by krishnapriawan**

### CODE REVIEW

**Comment by mlsaito** [comment]
@krishnapriawan Maybe instead of showing the JSON dump, we can just show the customer that it's possible to store the dataflow json to a a file, say `package.json`? Then on the `create` endpoint example 2, you can just point the request to `package.json` on example 2. Thoughts?

**Comment by krishnapriawan** [comment]
@mlsaito Good idea! I've just updated accordingly. Please let me know if there's any changes that we should make.

**Comment by mlsaito** [comment]
@krishnapriawan One last thing, let's also update the update package part. Thanks!

https://github.com/xplenty/xplenty-api-doc-v2/blob/master/sections/update-package.md

**Comment by krishnapriawan** [comment]
@mlsaito Certainly! Changes has just been updated

**Pull request merged**
